### PR TITLE
Pull other submissions: submittedWords updates with new post link submissions

### PR DESCRIPTION
**Pull request by zrfrere**
New submissions trigger a change to submittedWords array

### CODE REVIEW

**Comment by thair116** [comment]
Before I merge, can you delete the unneeded changes? The ones from the first attempt

The Files Changed tab is a bit messed up but git diff might help you better

**Comment by zrfrere** [comment]
Okay.  Should be cleaned up.  The only real change compared to the original is in the componentWillMount function, which now watches for changes.

**Comment by thair116** [comment]
Have you seen the diff? Can you figure out why so much of it is red?

**Comment by zrfrere** [comment]
I've cleaned things up a little more specifically:
1.  removed the log statement
2.  removed inline comments
3.  Changed tabs to spaces to hopefully accommodate the overall whitespace change

My review of the diff looks correct to me.  There are a lot of changes mostly due to whitespace.

**Review by thair116 — APPROVED** [review]
Looks great now. Thanks zach!

**Pull request merged**
